config/routes.rb
FieldTripServer::Application.routes.draw do
  resources :field_trips do
    get 'students', on: :member
  end
  resources :registrations
  resources :schools

  root 'field_trips#index'

end

app/models/field_trip.rb
class FieldTrip < ActiveRecord::Base
  belongs_to :school
  has_many :registrations
  
  has_many :students, through: :registrations
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :student
  belongs_to :field_trip

  validates_associated :student
  validates_associated :field_trip
  
  accepts_nested_attributes_for :student
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :field_trips
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :school
  has_many :registrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/field_trips_controller.rb
class FieldTripsController < ApplicationController
  before_action :set_field_trip, only: [:show, :edit, :update, :destroy, :students]

  # GET /field_trips
  # GET /field_trips.json
  def index
    @field_trips = FieldTrip.all
  end

  # GET /field_trips/1
  # GET /field_trips/1.json
  def show
  end
  
  def students
    @students = @field_trip.students
    respond_to do |format|
      format.html
      format.csv  {
        @filename = "#{@field_trip.name}.csv"
      }
    end
  end

  # GET /field_trips/new
  def new
    @field_trip = FieldTrip.new
  end

  # GET /field_trips/1/edit
  def edit
  end

  # POST /field_trips
  # POST /field_trips.json
  def create
    @field_trip = FieldTrip.new(field_trip_params)

    respond_to do |format|
      if @field_trip.save
        format.html { redirect_to @field_trip, notice: 'Field trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @field_trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @field_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /field_trips/1
  # PATCH/PUT /field_trips/1.json
  def update
    respond_to do |format|
      if @field_trip.update(field_trip_params)
        format.html { redirect_to @field_trip, notice: 'Field trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @field_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /field_trips/1
  # DELETE /field_trips/1.json
  def destroy
    @field_trip.destroy
    respond_to do |format|
      format.html { redirect_to field_trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field_trip
      @field_trip = FieldTrip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_trip_params
      params.require(:field_trip).permit(:name, :school_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]

  # GET /registrations
  # GET /registrations.json
  def index
    @registrations = Registration.all
  end

  # GET /registrations/1
  # GET /registrations/1.json
  def show
  end

  # GET /registrations/new
  def new
    @registration = Registration.new
  end

  # GET /registrations/1/edit
  def edit
  end

  # POST /registrations
  # POST /registrations.json
  def create
    @registration = Registration.new(registration_params)
    @registration.student = Student.find_or_create_by(registration_params[:student_attributes])
    respond_to do |format|
      if @registration.save
        format.html { redirect_to @registration, notice: 'Registration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @registration }
      else
        format.html { render action: 'new' }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registrations/1
  # PATCH/PUT /registrations/1.json
  def update
    respond_to do |format|
      if @registration.update(registration_params)
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1
  # DELETE /registrations/1.json
  def destroy
    @registration.destroy
    respond_to do |format|
      format.html { redirect_to registrations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:student_id, :field_trip_id, {student_attributes: [:id, :name, :school_id]})
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    # @schools = School.all
    @schools = School.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:board, :category, :school_type, :name, :address, :city, :province, :postal_code, :grades, :ecs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/field_trips_helper.rb
module FieldTripsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/field_trips/_form.html.erb
<%= form_for(@field_trip) do |f| %>
  <% if @field_trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field_trip.errors.count, "error") %> prohibited this field_trip from being saved:</h2>

      <ul>
      <% @field_trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br>
    <%= collection_select :field_trip, :school_id, School.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/field_trips/edit.html.erb
<h1>Editing field_trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @field_trip %> |
<%= link_to 'Back', field_trips_path %>

app/views/field_trips/index.html.erb
<h1>Listing field_trips</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @field_trips.each do |field_trip| %>
      <tr>
        <td><%= field_trip.name %></td>
        <td><%= field_trip.school.try(:name) %></td>
        <td><%= link_to 'Show', field_trip %></td>
        <td><%= link_to 'Edit', edit_field_trip_path(field_trip) %></td>
        <td><%= link_to 'Destroy', field_trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'Student List', students_field_trip_path(field_trip, format: :csv) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field trip', new_field_trip_path %>

app/views/field_trips/new.html.erb
<h1>New field_trip</h1>

<%= render 'form' %>

<%= link_to 'Back', field_trips_path %>

app/views/field_trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @field_trip.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @field_trip.school.try(:name) %>
</p>

<%= link_to 'Edit', edit_field_trip_path(@field_trip) %> |
<%= link_to 'Back', field_trips_path %>

app/views/field_trips/students.html.erb
<ol>
  <% @students.each do |student| %>
	<li> <%= student.name %> &dash; <%= student.school.name %></li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FieldTripServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :board %><br>
    <%= f.text_field :board %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :school_type %><br>
    <%= f.text_field :school_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :grades %><br>
    <%= f.text_field :grades %>
  </div>
  <div class="field">
    <%= f.label :ecs %><br>
    <%= f.check_box :ecs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<%= will_paginate @schools %>
<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Category</th>
      <th>School type</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Postal code</th>
      <th>Grades</th>
      <th>Ecs</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.board %></td>
        <td><%= school.category %></td>
        <td><%= school.school_type %></td>
        <td><%= school.name %></td>
        <td><%= school.address %></td>
        <td><%= school.city %></td>
        <td><%= school.province %></td>
        <td><%= school.postal_code %></td>
        <td><%= school.grades %></td>
        <td><%= school.ecs %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board:</strong>
  <%= @school.board %>
</p>

<p>
  <strong>Category:</strong>
  <%= @school.category %>
</p>

<p>
  <strong>School type:</strong>
  <%= @school.school_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @school.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @school.province %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @school.postal_code %>
</p>

<p>
  <strong>Grades:</strong>
  <%= @school.grades %>
</p>

<p>
  <strong>Ecs:</strong>
  <%= @school.ecs %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/shared/_header.html.erb
<nav>
  <ul>
	<li><%= link_to 'Schools', schools_path %></li>
	<li><%= link_to 'Field Trips', field_trips_path %></li>
	<li><%= link_to 'Registrations', registrations_path %></li>
  </ul>
</nav>